# Generated by Django 5.0 on 2024-02-08 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_alter_admin_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admin',
            table='adminapp_admin',
        ),
    ]
