# Generated by Django 5.0 on 2024-02-15 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_alter_admin_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='register',
            table='register_table',
        ),
    ]
