# Generated by Django 5.0 on 2024-02-16 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_packages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packages',
            old_name='tourpackages',
            new_name='tourpackage',
        ),
    ]
